server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:5695073_api.newimg.ltd.pfx
    key-store-type: PKCS12
    key-store-password: QDovK0vn
  servlet:
    session:
      timeout: 3600s
      cookie:
        secure: true
spring:
  datasource:
    username: Demo
    password: 12345
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver