spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: mail.qoop.top
    username: verify@qoop.top
    from: ACAT<${spring.mail.username}> # UnionLab作为发信昵称
    password: verify123421
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp.ssl.enable: true
  freemarker:
    cache: false
    settings:
      classic_compatible: true
    suffix: .html
    charset: UTF-8
    template-loader-path: classpath:/templates/
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/recruitsystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:e3h2qh4uhroefuhsgdbiol9u897}
#  mvc:
#    async:
#      request-timeout: 20000
wechat:
  appid: ${WECHAT_APP_ID:test}
  secret: ${WECHAT_APP_SECRET:test}
server:
#  tomcat:
#    connection-timeout: 20000
#    max-connections: 10000
#    accept-count: 3000
#    threads:
#      max: 400
#      min-spare: 10
  port: 8080
