#指定freemarker的模板路径和模板的后缀
spring:
  freemarker:
    template-loader-path: classpath:/webapp/
    suffix: :ftl
    # 指定字符集
    charset: utf-8
    # 指定是否要启用缓存
    cache: false

    #指定是否要暴露请求和会话属性
    expose-request-attributes: true
    expose-session-attributes: true
  # spring 静态资源扫描路径
  #下面这些内容是为了让MyBatis映射
  #指定Mybatis的Mapper文件
  web:
    resources:
      static-locations: classpath:/static/

  # THYMELEAF (ThymeleafAutoConfiguration)
  # 开启模板缓存（默认值： true ）
  thymeleaf:
    cache: true
    # 检查模板是否存在，然后再呈现
    check-template: true
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
    #Content-Type 的值（默认值： text/html ）
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 要被排除在解析之外的视图名称列表，⽤逗号分隔
    excluded-view-names:
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    mode: HTML5
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： :html ）
    suffix: .html
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #指定Mybatis的实体目录
  type-aliases-package: ltd.newimg.booksystem.model

  # 应用服务 WEB 访问端口

server:
  port: 8080
