spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/booksystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:e3h2qh4uhroefuhsgdbiol9u897}
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 应用服务 WEB 访问端口
server:
  port: 8080
#save_path: