server:
  port: 8081
  servlet:
    session:
      timeout: 3600s
spring:
  datasource:
    username: Demo
    password: 12345
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver